# Generated by Django 3.2.15 on 2023-09-02 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm23', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(blank=True, choices=[('Lecture', 'лекция'), ('Practice', 'практика'), ('Lab', 'лабораторная')], default='Lecture', max_length=40, null=True, verbose_name='Тип занятия'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='subgroup',
            field=models.CharField(blank=True, choices=[('Base-1', 'подгруппа 1'), ('Base-2', 'подгруппа 2'), ('Eng-1', 'подгруппа 1 (англ)'), ('Eng-2', 'подгруппа 2 (англ)')], default='Base-1', max_length=80, null=True, verbose_name='Название подгруппы'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='week_type',
            field=models.CharField(blank=True, choices=[('Odd', 'Нечетная'), ('Even', 'Четная')], default='Odd', max_length=40, null=True, verbose_name='Тип недели'),
        ),
    ]
